---
- name: stop database and related service on the current node to install patch
  environment:
    PATH: "{{ GI_ORACLE_HOME }}/bin:$PATH:/usr/bin"
  ansible.builtin.shell:
    cmd: "{{ script_loc }}/standby_db_stop_{{ ansible_host }}_prepatch.sh"
  register: db_stop
  tags:
    - stop_db
  failed_when: db_stop.rc not in [ 0, 1 ]

- name: display stop database status
  debug:
    var: db_stop.stdout_lines
  tags:
    - stop_db

- name: modify database oracle home location to cloned home on the current node
  environment:
    PATH: "{{ GI_ORACLE_HOME }}/bin:$PATH:/usr/bin"
  ansible.builtin.shell:
    cmd: "{{ script_loc }}/db_modify_{{ ansible_host }}.sh"
  register: db_modify
  ignore_errors: true
  tags:
    - db_modify
  failed_when: db_modify.rc not in [ 0, 1 ]

- name: display modify database oracle home location status
  debug:
    var: db_modify.stdout_lines
  tags:
    - db_modify

- name: replace oracle home entry with cloned home in /etc/oratab file
  become_user: root
  environment:
    PATH: "$PATH:/usr/bin"
  ansible.builtin.replace:
    path: /etc/oratab
    regexp: "{{ DR_ORACLE_HOME }}"
    replace: "{{ CL_DR_ORACLE_HOME }}"
    validate: /usr/bin/cat /etc/oratab %s
  register: oratab
  ignore_errors: true
  tags:
    - db_modify

- name: display /etc/oratab file
  become_user: root
  debug:
    var: oratab.stdout_lines
  tags:
    - db_modify

- name: switch grid infrastructure resources to cloned home
  become_user: root
  ansible.builtin.shell:
    cmd: export TEMP="{{patch_temp_dir}}";export TMPDIR="{{patch_temp_dir}}";export ORACLE_HOME="{{ GI_ORACLE_HOME }}";$ORACLE_HOME/OPatch/opatchauto apply -switch-clone -oh {{ GI_ORACLE_HOME }}
  register: opatch_switch
  throttle: 1
  tags:
    - oop_switch

- name: display switch grid infrastructure resources to cloned home status
  become_user: root
  debug:
    var: opatch_switch.stdout_lines
  tags:
    - oop_switch

- name: copy the grid infrastructure and database home patch apply log to a file
  become_user: root
  copy:
    content: "{{ opatch_switch.stdout }}"
    dest: "{{ log_dir }}/gi_opatch_switch_{{ ansible_host }}_{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
  ignore_errors: true
  tags:
    - oop_switch

- name: verify release update version on the grid infrastructure home
  ansible.builtin.shell:
    cmd: export ORACLE_HOME="{{ CL_GI_ORACLE_HOME }}";echo "The below patch instaled on oracle home $ORACLE_HOME";$ORACLE_HOME/OPatch/opatch lspatches
  ignore_errors: true
  register: gi_opatch_lsinv
  tags:
    - oop_switch_verify

- name: display grid infrastructure opatch lspatches output
  debug:
    var: gi_opatch_lsinv.stdout_lines
  tags:
    - oop_switch_verify

- name: start database on the current node
  environment:
    PATH: "{{ CL_GI_ORACLE_HOME }}/bin:$PATH:/usr/bin"
  ansible.builtin.shell:
    cmd: "{{ script_loc }}/standby_db_start_{{ ansible_host }}_postpatch.sh"
  register: start_db
  tags:
    - start_db
  failed_when: start_db.rc not in [ 0, 1 ]

- name: display start database output from the current node
  debug:
    var: start_db.stdout_lines
  tags:
    - start_db

- name: Execute SQL Statement to start MRP on standby database
  environment:
    PATH: "$PATH:/usr/bin"
  ansible.builtin.shell:
    cmd: "{{ script_loc }}/standby_db_open.sh"
  register: standby_db_mrp
  ignore_errors: true

- name: display standby database MRP status output
  debug:
    var: standby_db_mrp.stdout_lines

- name: Execute SQL Statement to get standby database  status
  environment:
    PATH: "$PATH:/usr/bin"
  ansible.builtin.shell:
    cmd: "{{ script_loc }}/standby_db_status.sh"
  register: standby_db_status
  ignore_errors: true

- name: display standby database status output
  debug:
    var: standby_db_status.stdout_lines

- name: copy the db component status output to a log file
  copy:
    content: "{{ standby_db_status.stdout }}"
    dest: "{{ log_dir }}/standby_db_status_{{ ansible_host }}_{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
  ignore_errors: true
