---
- name: Verify database type to apply or rollback patch
  ansible.builtin.shell:
    cmd: cd {{ ORACLE_HOME }}/rdbms/lib;ar -t libknlopt.a | grep -c kcsm.o
  register: db_type
  failed_when: db_type.rc not in [ 0, 1 ]

- name: display database type to apply or rollback patch
  debug:
    var: db_type.stdout

- name: Verify grid release update to apply or rollback patch
  ansible.builtin.shell:
    cmd: "{{ GI_ORACLE_HOME }}/bin/oraversion -compositeVersion"
  register: gi_release_version
  failed_when: gi_release_version.rc not in [ 0, 1 ]

- name: display grid release update to apply or rollback patch
  debug:
    var: gi_release_version.stdout

- include_tasks: ru_out_of_place_grid_clone_main.yml
  when: db_type.stdout == "0" and gi_release_version.stdout < "19.20.0.0.0"

- include_tasks: ru_rac_out_of_place_grid_clone_main.yml
  when: db_type.stdout != "0" and gi_release_version.stdout < "19.20.0.0.0"
