---
- name: copy release update to the local patch directory
  ansible.builtin.copy:
    src: "{{ patch_dir }}/{{ ojvm_patch_id }}"
    dest: "{{ patch_local_dir }}"
    remote_src: yes
    force: yes
    owner: oracle
    group: dba
  tags:
    - file_copy

- name: Verify patch conflict against database home
  ansible.builtin.shell:
    cmd: cd {{ patch_local_dir }}/{{ ojvm_patch_id }};export TMPDIR="{{patch_temp_dir}}";export ORACLE_HOME="{{ ORACLE_HOME }}";export PATH={{ ORACLE_HOME }}/OPatch:/usr/ccs/bin:$PATH;opatch prereq CheckConflictAgainstOHWithDetail -ph .
  register: db_home_conflict_status
  tags:
    - patch_conflict

- name: display database home patch conflict output
  debug:
    var: db_home_conflict_status.stdout_lines
  tags:
    - patch_conflict

- name: Verify patch conflict against database home 2
  ansible.builtin.shell:
    cmd: cd {{ patch_local_dir }}/{{ ojvm_patch_id }};export TMPDIR="{{patch_temp_dir}}";export ORACLE_HOME="{{ ORACLE_HOME_2 }}";export PATH={{ ORACLE_HOME_2 }}/OPatch:/usr/ccs/bin:$PATH;opatch prereq CheckConflictAgainstOHWithDetail -ph .
  register: db_home_conflict_status2
  tags:
    - patch_conflict

- name: display database home 2 patch conflict output
  debug:
    var: db_home_conflict_status2.stdout_lines
  tags:
    - patch_conflict
# - name: Verify patch conflict against finance database home
#   ansible.builtin.shell:
#     cmd: cd {{ patch_local_dir }}/{{ ojvm_patch_id }};export TMPDIR="{{patch_temp_dir}}";export ORACLE_HOME="{{ FIN_ORACLE_HOME }}";export PATH={{ FIN_ORACLE_HOME }}/OPatch:/usr/ccs/bin:$PATH;opatch prereq CheckConflictAgainstOHWithDetail -ph .
#   register: db_home_conflict_status
#   tags:
#     - patch_conflict
#   when:
#     - inventory_hostname == "us1-ulorarac01e.wil.csc.local"
#     - inventory_hostname == "us1-ulorarac01f.wil.csc.local"

# - name: display finance database home patch conflict output
#   debug:
#     var: db_home_conflict_status.stdout_lines
#   tags:
#     - patch_conflict
#   when:
#     - inventory_hostname == "us1-ulorarac01e.wil.csc.local"
#     - inventory_hostname == "us1-ulorarac01f.wil.csc.local"
