---
- name: backup grid infrastructure home
  become_user: root
  community.general.archive:
    path: "{{ GI_ORACLE_HOME }}"
    dest: "{{ patch_dir }}/orahomebackup/{{ ansible_hostname }}_{{ current_version }}_gi_{{ lookup('pipe', 'date +%m%d-%H%M') }}.tar.gz"
    format: gz
  tags:
    - gi_db_files_bkp

- name: backup database home
  become_user: root
  community.general.archive:
    path: "{{ ORACLE_HOME }}"
    dest: "{{ patch_dir }}/orahomebackup/{{ ansible_hostname }}_{{ current_version }}_db_1_{{ lookup('pipe', 'date +%m%d-%H%M') }}.tar.gz"
    format: gz
  tags:
    - gi_db_files_bkp

- name: backup database home 2
  become_user: root
  community.general.archive:
    path: "{{ ORACLE_HOME_2 }}"
    dest: "{{ patch_dir }}/orahomebackup/{{ ansible_hostname }}_{{ current_version }}_db_2_{{ lookup('pipe', 'date +%m%d-%H%M') }}.tar.gz"
    format: gz
  tags:
    - gi_db_files_bkp
