---
- name: Verify database type to apply or rollback patch
  ansible.builtin.shell:
    cmd: cd {{ CL_ORACLE_HOME }}/rdbms/lib;ar -t libknlopt.a | grep -c kcsm.o
  register: rb_db_type
  failed_when: rb_db_type.rc not in [ 0, 1 ]

- name: display database type to apply or rollback patch
  debug:
    var: rb_db_type.stdout

- name: Verify database release update to apply or rollback patch
  ansible.builtin.shell:
    cmd: "{{ CL_GI_ORACLE_HOME }}/bin/oraversion -compositeVersion"
  register: rb_gi_release_version
  failed_when: rb_gi_release_version.rc not in [ 0, 1 ]

- name: display database release update to apply or rollback patch
  debug:
    var: rb_gi_release_version.stdout

- include_tasks: rb_ru_out_of_place_switch_main.yml
  when: rb_db_type.stdout == "0" and rb_gi_release_version.stdout == "19.19.0.0.0"
# - include_tasks: rb_ru_rac_out_of_place_switch_main.yml
#   when: rb_db_type.stdout == "1" and rb_gi_release_version.stdout == "19.19.0.0.0"
