---
- name: Verify database type to apply or rollback patch
  ansible.builtin.shell:
    cmd: cd {{ ORACLE_HOME }}/rdbms/lib;ar -t libknlopt.a | grep -c kcsm.o
  register: db_type
  failed_when: db_type.rc not in [ 0, 1 ]

- name: display database type to apply or rollback patch
  debug:
    var: db_type.stdout

- name: Verify database release update to apply or rollback patch
  ansible.builtin.shell:
    cmd: "{{ ORACLE_HOME }}/bin/oraversion -compositeVersion"
  register: db_release_version
  failed_when: db_release_version.rc not in [ 0, 1 ]

- name: display database release update to apply or rollback patch
  debug:
    var: db_release_version.stdout

- include_tasks: standalone_ojvm_prerequisites_main.yml
  when: db_type.stdout == "0" and db_release_version.stdout < "19.20.0.0.0"

- include_tasks: rac_ojvm_prerequisites_main.yml
  when: db_type.stdout != "0" and db_release_version.stdout < "19.20.0.0.0"
