---
- name: clone the grid infrastructure home and install release update
  become_user: root
  ansible.builtin.shell:
    cmd: export TMPDIR="{{patch_temp_dir}}";export ORACLE_HOME="{{ GI_ORACLE_HOME }}";$ORACLE_HOME/OPatch/opatchauto apply {{ patch_local_dir }}/{{ gi_patch_id }} -prepare-clone -oh {{ GI_ORACLE_HOME }} -silent {{ script_loc }}/rac_gi_clone.properties -force_conflict
  register: gi_oop_clone
  throttle: 1
  tags:
    - gi_oop_clone

- name: display grid infrastructure home clone session log
  become_user: root
  debug:
    var: gi_oop_clone.stdout_lines
  tags:
    - gi_oop_clone

- name: copy grid infrastructure home clone session log to a file
  become_user: root
  copy:
    content: "{{ gi_oop_clone.stdout }}"
    dest: "{{ log_dir }}/gi_oop_clone_{{ ansible_host }}_{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
  tags:
    - gi_oop_clone

- name: verify release update apply on the cloned grid home
  ansible.builtin.shell:
    cmd: export ORACLE_HOME="{{ CL_GI_ORACLE_HOME }}";$ORACLE_HOME/OPatch/opatch lspatches
  register: gi_opatch_lsinv
  ignore_errors: true
  tags:
    - gi_oop_clone

- name: display list of patch installed on the cloned grid home
  debug:
    var: gi_opatch_lsinv.stdout_lines
  ignore_errors: true
  tags:
    - gi_oop_clone
