---
- name: Execute SQL Statement to get standby database  status
  environment:
    PATH: "$PATH:/usr/bin"
  ansible.builtin.shell:
    cmd: "{{ rac_script }}/standby_db_status.sh"
  register: standby_db_status
  ignore_errors: true

- name: display standby database status output
  debug:
    var: standby_db_status.stdout_lines

- name: copy the db component status output to a log file
  copy:
    content: "{{ standby_db_status.stdout }}"
    dest: "{{ log_dir }}/standby_db_status_{{ ansible_host }}_{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
  ignore_errors: true
