---
# us1-eastus:
#   children:
#     infra-sandbox:
#       children:
#         all:
#           hosts:
#             dlansible-orapatch-ci01:
#               ansible_host: 10.96.x.y
[ora_sand1]
# uloradbr16a.wil.csc.local ORACLE_SID=tssmt
 dlorarac01a.wil.csc.local ORACLE_SID=sbdbamt
 dlorarac01b.wil.csc.local ORACLE_SID=sbpsumt